# ---------- Build stage ----------
FROM maven:3.9.9-eclipse-temurin-24 AS build
WORKDIR /app
COPY . /app
RUN mvn -q -DskipTests=true clean package

# ---------- Runtime stage ----------
FROM eclipse-temurin:24-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8082
ENV PORT=8082
ENTRYPOINT ["java","-jar","/app/app.jar"]

